apiVersion: v1
kind: Service
metadata:
  name: users-service
spec:
  ports:
  - port: 8000
    targetPort: 8000
  selector:
    app: users
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: users
  labels:
    app: users
spec:
  selector:
    matchLabels:
      app: users
      tier: web
  template:
    metadata:
      labels:
        app: users
        tier: web
    spec:
      containers:
      - name: go-stocks
        image: us.gcr.io/naughty-nate-2020/users-hack:$GITHUB_SHA
        imagePullPolicy: Always
        ports:
        - containerPort: 8000